### ISSUE TITLE
Unnecessary entry in Manifest

### ISSUE THREAD

**Issue by CsabaMiomni** [Arasthel/SpannedGridLayoutManager#1]
Please remove the whole application entry from the Manifest file, because it will cause problems like this one:

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:34:9-36
  	is also present at [com.arasthel:spannedgridlayoutmanager:1.0.0] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:32:5-175:19 to override.

A lib like yours has to do nothing with the Application but the app itself.

**Comment by Arasthel** [comment]
You're right, my bad. I forgot to delete the auto-generated lines of the manifest. It should be fixed now in version 1.0.1.
