### ISSUE TITLE
Items not drawn 

### ISSUE THREAD

**Issue by prouland** [Arasthel/SpannedGridLayoutManager#19]
Hello there !

Thanks for the work on this library, it rocks ;)

By the way, I have an issue when scrolling up with this LayoutManager. Items are nicely recycled and drawn when scrolling down, by nothing is drawn on scolling up. An empty space with the good items heigh stays on top of the recyclerview, instead of the recycled views.

Has someone already experienced a similar issue ?

Edit: just to know, the same adapter code works fine with a classic GridLayoutManager.

**Comment by bendaniel10** [comment]
Hi @prouland I can confirm this issue exists too. Were you able to find a solution for it?

**Comment by bendaniel10** [comment]
Hi @prouland I believe I've discovered where the bug was coming from, this method: 

```kotlin
   protected fun fillBefore(position: Int, recycler: RecyclerView.Recycler, extraSpace: Int) {
        var position = position
        var limit = scroll - extraSpace

        val start = 0

        //~~~~~~This conditional assignment causes the error, limit is always zero 
       //after this and the block in the while won't execute, making the views not to be
       // recycled correctly. I'm still investigating the effects of removing this block because 
       //the issue goes away when I remove this block.~~~~~~/
        if (limit < start) {
            limit = start
        }

        while (canAddMoreViews(Direction.START, limit) && position >= 0) {
            makeAndAddView(position, Direction.START, recycler)
            position--
        }
    }
```

https://github.com/bendaniel10/SpannedGridLayoutManager/blob/81bf6edeb543d1b473f84554e04532643244c059/spannedgridlayoutmanager/src/main/java/com/arasthel/spannedgridlayoutmanager/SpannedGridLayoutManager.kt#L588

**Comment by seamfix** [comment]
Hi @prouland  This has been solved here: https://github.com/Arasthel/SpannedGridLayoutManager/issues/15 Adding an item decorator seems to solve this.

**Comment by bendaniel10** [comment]
Hi @prouland this has been solved here: https://github.com/Arasthel/SpannedGridLayoutManager/issues/15 adding an item decorator solves this issue.

**Comment by prouland** [comment]
Hi @bendaniel10 
Thanks for sharing a workaround.
Since I was not able to find a fix, I finally got the Nick Butcher LayoutManager : https://github.com/nickbutcher/plaid/blob/grid_span/app/src/main/java/io/plaidapp/ui/recyclerview/SpannedGridLayoutManager.java

**Comment by Arasthel** [comment]
@prouland I was uploading a new version as you wrote the message 😅. Sorry for the long delay, I haven't had much free time to work on my libraries lately.

**Comment by Arasthel** [comment]
Also, thanks to @bendaniel10 for the tip, it probably saved me hours of debugging 👍
