### ISSUE TITLE
Change minSDKVersion

### ISSUE THREAD

**Issue by javierugarte** [Arasthel/SpannedGridLayoutManager#3]
Is it possible to decrease minSDKVersion?

**Comment by FabianTerhorst** [comment]
+1 for api 14

**Comment by Arasthel** [comment]
minSDKDVersion is now **14**. Changed it in 45bdee4, version 1.0.2. 

I was using a higher version because I was planning on using `paddingStart` and `paddingEnd`, but as they weren't used in the end everything should work on API 14.

**Comment by FabianTerhorst** [comment]
Great, thanks.
