### ISSUE TITLE
item can't see until scroll,data is from net,local data have not the problem

### ISSUE THREAD

**Issue by xwtao** [Arasthel/SpannedGridLayoutManager#30]

**Comment by Arasthel** [comment]
Can you elaborate a bit? Show some of your code? Specially the adapter and how you update it.

**Comment by DennyWeinberg** [comment]
Same here

**Comment by Arasthel** [comment]
> Same here



> Can you elaborate a bit? Show some of your code? Specially the adapter and how you update it.

**Comment by DennyWeinberg** [comment]
Here is my layout file:
`<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:layout_behavior="com.levionsoftware.photos.workarounds.FixAppBarLayoutBehavior">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:collapsedTitleTextAppearance="@style/CollapsingToolbarLayoutStyleText"
            app:contentScrim="?attr/_colorPrimary"
            app:expandedTitleMarginEnd="16dp"
            app:expandedTitleMarginStart="16dp"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:clickable="true"
                android:focusable="true">

                <ImageView
                    android:id="@+id/main_subset_image_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:foreground="?android:attr/selectableItemBackground" />

                <TextView
                    android:id="@+id/date_text_view"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="8dp"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    style="@style/CTStyleTextBold" />

            </androidx.constraintlayout.widget.ConstraintLayout>

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <include layout="@layout/ads_view" />
        </LinearLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <LinearLayout
        android:id="@+id/main_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            style="@style/Widget.MaterialComponents.TabLayout.Colored"
            app:tabIndicatorColor="?attr/_colorAccent"
            android:background="?attr/_colorPrimaryToolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            app:tabGravity="center"
            app:tabMode="fixed" />
        

        <androidx.viewpager.widget.ViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </LinearLayout>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/subset_fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="16dp"
        android:src="@drawable/ic_share_white_48dp"
        app:layout_anchor="@id/main_view"
        app:layout_anchorGravity="bottom|right|end" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>`

The viewpager contains my rv Fragment, so this could also be the "problem".

**Comment by tofijak** [comment]
I have the same problem. I'm using Glide to load images. Initially empty, but loads when I scroll.

Here is my adapter.

    public class MasonryAdapter extends RecyclerView.Adapter<MasonryAdapter.MasonryView> {
       private Context context;
       private ArrayList<Image> imageList;

    public MasonryAdapter(Context context, ArrayList<Image> imageList) {
        this.context = context;
        this.imageList = imageList;
    }

    @NonNull
    @Override
    public MasonryView onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new MasonryView(LayoutInflater.from(parent.getContext())
                .inflate(R.layout.tile, parent, false));
    }

    @Override
    public void onViewAttachedToWindow(@NonNull final MasonryView holder) {
        super.onViewAttachedToWindow(holder);
    }

    @Override
    public void onBindViewHolder(@NonNull final MasonryView holder, final int position) {
            Glide.with(context).load(imageList.get(position).getImageUrl()).into(holder.imageView);
    }

    @Override
    public int getItemCount() {
        return imageList.size();
    }

    static class MasonryView extends RecyclerView.ViewHolder {
        private ImageView imageView;

        public MasonryView(View itemView) {
            super(itemView);
            imageView = itemView.findViewById(R.id.imagemason);
        }
    }

**Comment by Arasthel** [comment]
This is probably fixed on version 3.0.1. Could you test it?

**Comment by DennyWeinberg** [comment]
I will try it.

**Comment by DennyWeinberg** [comment]
See #38
