### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by forntoh** [Arasthel/SpannedGridLayoutManager#32]
I am unable to use the lib, I get the following error

```java
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.<init>(SpannedGridLayoutManager.kt)
        at cm.diginov.isitravel.activities.Home.HomeActivity.onCreate(HomeActivity.java:43)
```

This is how I use it
```java
SpannedGridLayoutManager spannedGridLayoutManager = new SpannedGridLayoutManager(SpannedGridLayoutManager.Orientation.VERTICAL, 3);
spannedGridLayoutManager.setItemOrderIsStable(true);
rv_trips.setLayoutManager(spannedGridLayoutManager);
rv_trips.setAdapter(tripsAdapter);
```

**Comment by Arasthel** [comment]
It looks like you have to add support for Kotlin in your Java project by adding this to your app's `build.gradle`:

```groovy
implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.2.71'
```

I'll think about adding a small section in the README about this.

**Comment by forntoh** [comment]
> It looks like you have to add support for Kotlin in your Java project by adding this to your app's `build.gradle`:
> 
> ```groovy
> implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.2.71'
> ```
> 
> I'll think about adding a small section in the README about this.

Thanks
