### ISSUE TITLE
Items are on bottom when small number

### ISSUE THREAD

**Issue by jaumard** [Arasthel/SpannedGridLayoutManager#5]
Looks ok when you have a lot of items, but when you have few of them it look like this: 

![device-2017-10-01-164151](https://user-images.githubusercontent.com/2970449/31055712-72b9d312-a6c7-11e7-9c9b-fbe4565265e5.png)

To reproduce just take your sample app and replace 500 by 4 on getItemCount of the adapter

PS: tested on Android O on Nexus 5X

**Comment by Arasthel** [comment]
Thanks for reporting! This should be fixed in ae493f06216af2cf1dffa6c9d8311fa00b3391aa. Looking into #6 now before I release another version.

**Comment by jaumard** [comment]
Just tested works great thanks for the quick fix ! :D 
I search for this one but didn't know where to look, lot of stuff going on in this class
#6 is more tricky I think ^^

**Comment by bendaniel10** [comment]
Hello @Arasthel This problem still exists. 

When creating the Adapter if it is initialised with items, it works well.

However, if the list in the adapter is updated and `notifyDatasetChanged()` is called, it will still wrongly align the items to the bottom.
