### ISSUE TITLE
Complex layout doesn't work

### ISSUE THREAD

**Issue by jaumard** [Arasthel/SpannedGridLayoutManager#6]
I'm trying to use this layout: 

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:card_view="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools">

    <data>

        <import type="android.view.View"/>

        <variable
            name="data"
            type="com.mylisabox.network.devices.models.Device"/>

        <variable
            name="viewModel"
            type="com.mylisabox.lisa.device.viewmodels.DeviceViewModel"/>
    </data>

    <android.support.v7.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:layout_margin="@dimen/activity_vertical_margin"
        android:backgroundTint="@android:color/holo_green_light"
        card_view:cardCornerRadius="4dp"
        card_view:cardElevation="@dimen/cardview_default_elevation">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/holo_green_dark"
            android:orientation="vertical">

            <LinearLayout
                android:id="@+id/widgetHeader"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/holo_red_dark"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingRight="@dimen/space_normal">

                <TextView
                    android:id="@+id/widgetTitle"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:padding="@dimen/space_normal"
                    android:text="@{data.name}"
                    android:textAppearance="?android:textAppearanceLarge"
                    android:textStyle="bold"
                    tools:text="My widget"/>

                <com.mylisabox.common.ui.ToggleImageButton
                    android:id="@+id/widgetFavorite"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@null"
                    android:checked="@{data.favorite}"
                    android:src="@drawable/ic_favorite_24dp"
                    android:tint="@drawable/ic_color_selector"/>
            </LinearLayout>

            <View
                style="@style/Divider"/>

            <LinearLayout
                android:id="@+id/widgetContent"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                android:orientation="vertical"/>
        </LinearLayout>
    </android.support.v7.widget.CardView>
</layout>
```
Witch look like: 
<img width="320" alt="capture d ecran 2017-10-01 a 20 21 37" src="https://user-images.githubusercontent.com/2970449/31057630-3a67f344-a6e6-11e7-81b1-6f2c61cfac0d.png">

But I have this:
![device-2017-10-01-202331](https://user-images.githubusercontent.com/2970449/31057639-6c3a0b00-a6e6-11e7-981b-8c0a655e3fe2.png)

If I force size of the card view's content I have this:
![force-device-2017-10-01-202031](https://user-images.githubusercontent.com/2970449/31057627-27d62c6e-a6e6-11e7-9c42-3e5f664becdf.png)

On my adapter I have like the sample:
```
val width = 4
val height = 3
holder.itemView.layoutParams = RecyclerView.LayoutParams(width, height)
```

And I think that's the problem, somewhere it need to refresh sub component of the `itemView`. 
I also try more complex layout with the sample app but wasn't able to make it work.

Am I doing something wrong ? Is there any other example more complex in another repo ?

**Comment by jaumard** [comment]
I can try to dig into this, if you have an idea of where to look in your code it would be really helpful ^^ 
Thanks

**Comment by Arasthel** [comment]
As I feared, this requires breaking API changes...

At first I thought `LayoutParams.width` and `LayoutParams.height` were ignored when measuring and only *top, right, bottom, left* were used. I was wrong, so a new kind of LayoutParams will be needed to declare the `SpanSize` since *width and height* variables are not available for this.

I will try to update the docs and release a new version tomorrow.

**Comment by jaumard** [comment]
That was my understanding too :/ my idea was a missing requestLayout or invalidate on children but with those value under layoutParams it didn't work. 
Hope it's not a lot of changes on your side impressive work you did with library congrats and thanks :)

**Comment by jaumard** [comment]
Any news on this @Arasthel ? Need help ?

**Comment by jaumard** [comment]
I try with a customer LayoutParams but it appear that it doesn't fix the problem completely 
![device-2017-10-15-175309](https://user-images.githubusercontent.com/2970449/31586466-c3dd7ee6-b1d1-11e7-8c40-954778c22998.png)
![device-2017-10-15-175252](https://user-images.githubusercontent.com/2970449/31586468-c3fd9924-b1d1-11e7-8191-b88b07df3f3c.png)

at first the content is empty, when I click it update the size and  the content fit correctly, if I click a second time it restore the initial size and become empty again :( 
Any idea @Arasthel ?

**Comment by Arasthel** [comment]
I'm sorry, I've had a really busy couple of weeks and some other issues took precedence. I have just uploaded a new branch, could you test your layout with 7d2864d8c6d3656de69b3b4692f68dadb7dcafd7 version?

**Comment by jaumard** [comment]
No problem @Arasthel :) 
After a quick test look like it work great ! I'll test more this tomorrow see if there some corner cases or refresh problem with screen rotation and stuff but basic test is more than OK ! Thanks :)

**Comment by jaumard** [comment]
I test more deeply and found no problem at all :) I just play with the sample app by adding my complex layout inside and work really great. Just a small things SpanSize should be by default 1:1 not 0:0 in my opinion.
Let me know when you release this fix I'll update my app right away :) 
Thanks again !

**Comment by jaumard** [comment]
Hi @Arasthel, any news on the update ? :)

**Comment by Arasthel** [comment]
I just uploaded version 2.0 with those fixes as well as your suggested exceptions. Thanks!

**Comment by jaumard** [comment]
Thanks @Arasthel ! :D I will test this asap
